server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/go_http?allowMultiQueries=true&autoReconnect=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000
#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: enableFlag
#      logic-delete-value: 0
#      logic-not-delete-value: 1
#  mapper-locations: classpath:/mybatis/*.xml
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.hangtalk.webapi.entry
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true

swaggerConfig:
  swagger-ui-open: true

